import { Mudanza, AgenteInternacional } from "@/types/mudanza";

export const mockMudanzas: Mudanza[] = [
  {
    id: "1",
    numero: "MUD-2025-001",
    cliente: {
      id: "c1",
      nombre: "María Rodríguez",
      email: "maria.rodriguez@example.com",
      telefono: "+57 312 456 7890",
      tipo: "individual",
    },
    origen: {
      pais: "Colombia",
      ciudad: "Bogotá",
      direccion: "Calle 100 #15-20",
    },
    destino: {
      pais: "Estados Unidos",
      ciudad: "Miami",
      direccion: "123 Brickell Ave",
    },
    estado: "transito",
    tipo: "internacional",
    modo: "maritimo",
    fechaCreacion: "2025-01-15",
    fechaEstimada: "2025-02-28",
    volumenEstimado: 45.5,
    pesoEstimado: 3200,
    valorDeclarado: 25000,
    agente: {
      id: "a1",
      nombre: "Harmony Relocation",
      pais: "Estados Unidos",
      ciudad: "Miami",
    },
    coordinador: {
      id: "coord1",
      nombre: "Juan Díaz",
      email: "juan.diaz@abcmoving.com",
    },
    progreso: 65,
    prioridad: "alta",
  },
  {
    id: "2",
    numero: "MUD-2025-002",
    cliente: {
      id: "c2",
      nombre: "Carlos Mendoza",
      email: "carlos.mendoza@corp.com",
      telefono: "+57 301 234 5678",
      tipo: "corporativo",
    },
    origen: {
      pais: "Colombia",
      ciudad: "Medellín",
      direccion: "Carrera 43A #1-50",
    },
    destino: {
      pais: "España",
      ciudad: "Madrid",
      direccion: "Calle Serrano 45",
    },
    estado: "empaque",
    tipo: "corporativa",
    modo: "aereo",
    fechaCreacion: "2025-01-20",
    fechaEstimada: "2025-02-15",
    volumenEstimado: 28.3,
    pesoEstimado: 1800,
    valorDeclarado: 35000,
    agente: {
      id: "a2",
      nombre: "FIDI Global",
      pais: "España",
      ciudad: "Madrid",
    },
    coordinador: {
      id: "coord1",
      nombre: "Juan Díaz",
      email: "juan.diaz@abcmoving.com",
    },
    progreso: 35,
    prioridad: "urgente",
  },
  {
    id: "3",
    numero: "MUD-2025-003",
    cliente: {
      id: "c3",
      nombre: "Embajada de Francia",
      email: "relocation@embassy-france.co",
      telefono: "+57 320 555 1234",
      tipo: "diplomatico",
    },
    origen: {
      pais: "Colombia",
      ciudad: "Bogotá",
      direccion: "Carrera 11 #93-12",
    },
    destino: {
      pais: "Francia",
      ciudad: "París",
      direccion: "Avenue des Champs-Élysées 125",
    },
    estado: "booking",
    tipo: "diplomatica",
    modo: "aereo",
    fechaCreacion: "2025-01-25",
    fechaEstimada: "2025-02-20",
    volumenEstimado: 65.8,
    pesoEstimado: 4500,
    valorDeclarado: 85000,
    coordinador: {
      id: "coord2",
      nombre: "Ana López",
      email: "ana.lopez@abcmoving.com",
    },
    progreso: 20,
    prioridad: "alta",
  },
];

export const mockAgentes: AgenteInternacional[] = [
  {
    id: "a1",
    nombre: "Harmony Relocation",
    pais: "Estados Unidos",
    ciudad: "Miami",
    cobertura: ["USA", "Canadá", "México"],
    servicios: ["Mudanza puerta a puerta", "Almacenamiento", "Gestión aduanera"],
    certificaciones: ["FIDI", "IAM", "ISO 9001"],
    sla: 30,
    moneda: "USD",
    contacto: {
      nombre: "John Smith",
      email: "john@harmonyrelocation.com",
      telefono: "+1 305 555 0123",
    },
    rating: 4.8,
    mudanzasCompletadas: 245,
    tasaCumplimiento: 96,
  },
  {
    id: "a2",
    nombre: "FIDI Global",
    pais: "España",
    ciudad: "Madrid",
    cobertura: ["España", "Portugal", "Francia", "Italia"],
    servicios: ["Mudanza internacional", "Reubicación corporativa", "Pet relocation"],
    certificaciones: ["FIDI", "LACMA"],
    sla: 25,
    moneda: "EUR",
    contacto: {
      nombre: "María García",
      email: "maria@fidiglobal.es",
      telefono: "+34 91 555 0234",
    },
    rating: 4.9,
    mudanzasCompletadas: 312,
    tasaCumplimiento: 98,
  },
];
